### ISSUE TITLE
Ability lo load files from computer is missing

### ISSUE THREAD

**Issue by pastukhov** [chilipeppr/workspace-nodemcu#3]
I can't find the way to upload a file from computer to board.
Please add ability to load files from computer to MCU.

**Comment by chilipeppr** [comment]
That is a core feature already there. Maybe it's just confusing.

[image: Inline image 1]

You have to just hit
[image: Inline image 2]

You need to make sure your device is connected and working though, where
it's taking commands correctly. The nodemcu can tend to get stuck so just
hit Reset.

[image: Inline image 3]

**Comment by pastukhov** [comment]
Imsges is lost?

**Comment by chilipeppr** [comment]
---------- Forwarded message ----------
From: John Lauer <jlauer12@gmail.com>
Date: Wed, Feb 17, 2016 at 8:04 AM
Subject: Re: [workspace-nodemcu] Ability lo load files from computer is
missing (#3)
To: chilipeppr/workspace-nodemcu <
reply@reply.github.com
>
Cc: chilipeppr/workspace-nodemcu <workspace-nodemcu@noreply.github.com>


That is a core feature already there. Maybe it's just confusing.

[image: Inline image 1]

You have to just hit
[image: Inline image 2]

You need to make sure your device is connected and working though, where
it's taking commands correctly. The nodemcu can tend to get stuck so just
hit Reset.

[image: Inline image 3]

**Comment by chilipeppr** [comment]
![image](https://cloud.githubusercontent.com/assets/7904621/13135486/d1c98106-d5c5-11e5-8240-a095bfa25127.png)

**Comment by pastukhov** [comment]
Upload button is uploading currently open file (unnamed1.lua). But not a file from the host computer.
To be clear. I have a set of files on PC: 

```
configNetSmart.lua
ds3231.lua
gpioInit.lua
init.lua
initTime.lua
settime.lua
syncTime.lua
```

Usualy i'm uploading my files to MCU with Makfile:

```
######################################################################
# User configuration
######################################################################
# Path to nodemcu-uploader (https://github.com/kmpm/nodemcu-uploader)
NODEMCU-UPLOADER=python ../nodemcu-uploader/nodemcu-uploader.py --start_baud 9600 --baud 115200
# Serial port
PORT=/dev/ttyUSB0

######################################################################
# End of user config
######################################################################
LUA_FILES := $(wildcard *lua)

# Upload all
all: $(LUA_FILES)
    @$(NODEMCU-UPLOADER) -p $(PORT) upload $(foreach f, $^, $(f))
```

**Comment by chilipeppr** [comment]
That's how it works. You'd have to paste in a file to a new window to get
the upload button to upload other files.

**Comment by pastukhov** [comment]
Ok, but this is uncomfortable.

**Comment by chilipeppr** [comment]
Please feel free to fork the workspace and modify any way you'd like.
That's the beauty of ChiliPeppr. If you have any changes you think are
compelling and want to do a pull request to the core workspace I'm more
than happy to add great features.

**Comment by chilipeppr** [comment]
Artem, check out the video I made to help you understand the workflow.
Perhaps you'll find my approach makes more sense if you start all of your
development inside the workspace as opposed to externally where you have
files on your local hard drive.

https://www.youtube.com/watch?v=gudsZeGGoBM

**Comment by pastukhov** [comment]
Thanks for the video.
What if i want to develop on top of existing project?
Look at https://github.com/marcoskirsch/nodemcu-httpserver. It contain about 10 core lua files and variable amount of different files on it http root folder. Not only lua, but html, js, images ...
